In [9]:
import torch
test_seq = torch.zeros((50,))

def gen_mut_batch(seq, num_samples, max_muts):
    L = seq.shape[0]
    mut_sites = torch.randint(0, L, (num_samples*max_muts,))
    mut_batch_ind = torch.tile(torch.arange(0, num_samples).reshape(-1, 1), (1, max_muts)).flatten()
    base_residues = seq[mut_sites]
    mut_mask = torch.rand(mut_sites.shape) > 0.2
    mut_residues = torch.randint(0, 23, mut_sites.shape)*mut_mask + base_residues*(~mut_mask)
    mut_batch = torch.tile(seq.reshape(1, -1), (num_samples, 1))
    mut_batch[mut_batch_ind, mut_sites] = mut_residues
    return mut_batch

mut_batch = gen_mut_batch(test_seq, 12, 5)
print(mut_batch)

tensor([[ 0., 18.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0., 13.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0., 20.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0., 19.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 11.,
          0.,  0.,  0.,  0.,  0.,  9.,  0.,  2.,  0.,  0.,  0.,  0.,  0., 19.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0., 17.,  0.,
          0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  

In [6]:
mut_sites = torch.randint(0, 312, (12, 5))
seq = torch.range(0, 312)
print(mut_sites)
print(seq[mut_sites])

tensor([[ 28, 130, 232, 248, 217],
        [113, 277,  66,   4, 300],
        [201, 151, 264, 291, 296],
        [ 82, 237, 233, 283, 136],
        [119,  57,  97,  82, 264],
        [270, 257,  98, 225,  85],
        [124, 101,  59,  91,  97],
        [ 51,   2, 289, 125, 134],
        [260, 295, 187, 134, 231],
        [126, 262,  21, 260,   9],
        [ 98,  65, 163, 239,  16],
        [131, 182, 135, 306,  82]])
tensor([[ 28., 130., 232., 248., 217.],
        [113., 277.,  66.,   4., 300.],
        [201., 151., 264., 291., 296.],
        [ 82., 237., 233., 283., 136.],
        [119.,  57.,  97.,  82., 264.],
        [270., 257.,  98., 225.,  85.],
        [124., 101.,  59.,  91.,  97.],
        [ 51.,   2., 289., 125., 134.],
        [260., 295., 187., 134., 231.],
        [126., 262.,  21., 260.,   9.],
        [ 98.,  65., 163., 239.,  16.],
        [131., 182., 135., 306.,  82.]])


/tmp/ipykernel_1402833/2960507556.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  seq = torch.range(0, 312)


In [ ]:
import Bio.